# Generated by Django 3.1 on 2021-02-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched', models.CharField(max_length=5000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
