# Generated by Django 3.1 on 2021-02-10 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='searched',
        ),
        migrations.AddField(
            model_name='search',
            name='Searched',
            field=models.CharField(default=datetime.datetime(2021, 2, 10, 15, 18, 17, 408677, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
