# Generated by Django 3.1 on 2021-02-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210210_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Searched',
            new_name='searched',
        ),
    ]
