# Generated by Django 3.1 on 2021-02-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210210_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
