# Generated by Django 3.1 on 2021-02-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210210_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searched',
            field=models.CharField(default='programming', max_length=500, null=True),
        ),
    ]
