# Generated by Django 3.1 on 2021-02-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210211_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
