# Generated by Django 3.1 on 2021-02-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
